using Common.Exceptions;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Repository;

public interface IIncrementRepository
{
    Task<IncrementKey?> GetIncrement(string key);
    Task<List<IncrementKey>> GetAllIncrements();
    void RemoveIncrement(string key);
    Task<IncrementKey> UpsertIncrement(IncrementCommand command);
}


internal class IncrementRepository : IIncrementRepository
{
    private readonly ILogger<IncrementRepository> _logger;
    private readonly IncrementContext _context;

    public IncrementRepository(ILogger<IncrementRepository> logger, IncrementContext context)
    {
        _logger = logger;
        _context = context;
    }

    async Task<List<IncrementKey>> IIncrementRepository.GetAllIncrements()
    {
        return await _context.Keys
            .AsNoTracking()
            .Select(i => i.ToDto())
            .ToListAsync()
            .ConfigureAwait(false);
    }

    async Task<IncrementKey?> IIncrementRepository.GetIncrement(string key)
    {
        Entities.Keys? result = await _context.Keys.AsNoTracking().FirstOrDefaultAsync(i => i.IncrementKey == key).ConfigureAwait(false);

        return result?.ToDto();
    }

    void IIncrementRepository.RemoveIncrement(string key)
    {
        throw new NotImplementedException();
    }

    async Task<IncrementKey> IIncrementRepository.UpsertIncrement(IncrementCommand command)
    {
        Entities.Keys? existing = await _context.Keys
            .AsTracking()
            .FirstOrDefaultAsync(i => i.IncrementKey == command.Key)
            .ConfigureAwait(false);

        if (existing is null)
        {
            // Create new increment
            var newIncrement = new Entities.Keys
            {
                Id = 0, // Will be auto-generated by database
                IncrementKey = command.Key,
                PreviousValue = command.PreviousValue ?? 0,
                LastUsed = DateTimeOffset.UtcNow
            };

            _context.Keys.Add(newIncrement);
            await _context.SaveChangesAsync().ConfigureAwait(false);

            return newIncrement.ToDto();
        }
        else
        {
            // Key exists - check if new value is valid
            if (command.PreviousValue.HasValue && command.PreviousValue < existing.PreviousValue)
            {
                throw new BadRequestException($"Cannot set PreviousValue to {command.PreviousValue} because current value is {existing.PreviousValue}. New value must be greater than or equal to current value.");
            }

            // Update existing increment
            existing.PreviousValue = command.PreviousValue ?? 0L;
            existing.LastUsed = DateTimeOffset.UtcNow;

            await _context.SaveChangesAsync().ConfigureAwait(false);

            return existing.ToDto();
        }
    }
}
